import type { Metadata } from "next";
import "./globals.css";
import { AppStateProvider } from "@/state/AppStateProvider";

export const metadata: Metadata = {
  title: "imeal",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="min-h-screen">
        <AppStateProvider>{children}</AppStateProvider>
      </body>
    </html>
  );
}
